# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TearDrop"
base_uri: '/teardrop'

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"
auto_page: 1

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
  JSON:
    convert_blessed: 1
    allow_blessed: 1
    allow_unknown: 1
    
# For session support enable the following line and see Dancer::Session
session: "YAML"

plugins:
  DBIC:
    default:
      dsn: dbi:Pg:dbname=teardrop
      schema_class: TearDrop::Model
      user: teardrop
      options:
        RaiseError: 1
        PrintError: 1
